import { Inter } from "next/font/google";
import Providers from "@/providers/providers";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import MainProvider from "../providers/MainProvider";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Providers>
          <MainProvider>
            <Header />
            {children}
            <Footer />
          </MainProvider>
        </Providers>
      </body>
    </html>
  );
}
